// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBKslBjLLLgyrkbEg_EReELWm9frKNzgc',
    appId: '1:179584675585:web:83417af9ab45ad31577500',
    messagingSenderId: '179584675585',
    projectId: 'foodpin-d001c',
    authDomain: 'foodpin-d001c.firebaseapp.com',
    storageBucket: 'foodpin-d001c.firebasestorage.app',
    measurementId: 'G-RPJBVZPG2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ6IgrNbWu2ZXtWtJ_liVrjm2e5yTsHPY',
    appId: '1:179584675585:android:9fc93776641bbc39577500',
    messagingSenderId: '179584675585',
    projectId: 'foodpin-d001c',
    storageBucket: 'foodpin-d001c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOx7fona_M4Q2WX1ce82vsAKWsibE5Hdw',
    appId: '1:179584675585:ios:2856d772b70200f1577500',
    messagingSenderId: '179584675585',
    projectId: 'foodpin-d001c',
    storageBucket: 'foodpin-d001c.firebasestorage.app',
    iosBundleId: 'com.barowoori.foodpin',
  );
}
